led_irr = LED0 # pin attached to LED that indicates irrigation need
fan_pin = D22.PWM # pin attached to fan module

soil_pin = A6 #D36
light_pin = A4 #D38

### MODIFICARE I SEGUENTI PARAMETRI

WIFI_SSID = ""
WIFI_PW = ""


# paste here your device id and password generated by the ZDM
# the password is a jwt generated from a device's key
device_id = ''
password = ''


soglia_soil = 2000
soglia_temp = 30
soglia_hum = 60

# weights = [random(1,10)/random(1,10) for i in range(36)] #36 weights
weights = [-0.065, 0.231, -0.042, -0.272, -0.01, -0.039, 
0.271, 0.482, 0.341, -0.113, 0.396, 0.216, 
0.321, -0.137, -0.307, -0.035, -0.207, 0.461, 
0.265, 0.321, 0.006, -0.139, 0.259, -0.449,
-0.103, -0.436, 0.22, -0.019, 0.272, -0.224,
0.263, -0.348, -0.383, -0.36, 0.303, 0.016]
