led_irr = LED0 # pin attached to LED that indicates irrigation need
fan_pin = D22.PWM # pin attached to fan module

soil_pin = A6 #D36
light_pin = A4 #D38

### MODIFICARE I SEGUENTI PARAMETRI

WIFI_SSID = "Zerynth1"
WIFI_PW = "zerynthwifi1"

# paste here your device id and password generated by the ZDM
# the password is a jwt generated from a device's key
device_id = 'dev-53fqofku77zs'
password = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXYtNTNmcW9ma3U3N3pzIiwidXNlciI6ImRldi01M2Zxb2ZrdTc3enMiLCJrZXkiOjEsImV4cCI6MjUxNjIzOTAyMn0.W7pxGBbM8PElbg8zuPTle_nvMYNg_0rMlb7OWCIPnwI'

soglia_soil = 2000
soglia_temp = 30
soglia_hum = 60

