led_irr = LED0 # pin attached to LED that indicates irrigation need
fan_pin = D22.PWM # pin attached to fan module

soil_pin = A6
light_pin = A4

### MODIFICARE I SEGUENTI PARAMETRI

WIFI_SSID = ""
WIFI_PW = ""

# paste here your device id and password generated by the ZDM
# the password is a jwt generated from a device's key
device_id = ''
password = ''

soglia_soil = 1000
soglia_temp = 30
soglia_hum = 60

